### ISSUE TITLE
Post-RPGLB to-do

### ISSUE THREAD

**Issue by shenef** [shenef/FFX-TAS#1]
- [ ] optimize TAS segment per segment (movement, strats, etc)
- [ ] touch save sphere only under set conditions (hp, mp etc)
- [ ] make it work with any item and skill configuration (atm parameter boosters break the TAS)
- [ ] split the battle, memory and other very long files
- [ ] remove `recordBlitzResults_Tyton()`
- [ ] remove `escapeAll`
- [ ] fix circular references (pycycle: xbox -> memory.main: Line 3 -> logs: Line 3 =>> xbox)
- [ ] remove seed specific code
- [ ] remove unneeded tracker files
- [x] rewrite readme
- [x] add install instructions to the readme
- [ ] check for 1/101 Status Fails
- [ ] clean up functions related to Rikkus Overdrive
- [ ] more Spare Change steps
